// <auto-generated />
using System;
using ExecutorBalancer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExecutorBalancer.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BalancerDbContext))]
partial class BalancerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ExecutorBalancer.Domain.Assignment", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<long>("OrderId")
                .HasColumnType("bigint");

            b.Property<long>("ExecutorId")
                .HasColumnType("bigint");

            b.Property<string>("Kind")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<decimal>("OrderWeight")
                .HasColumnType("numeric(10,3)")
                .HasPrecision(10, 3);

            b.Property<decimal>("Score")
                .HasColumnType("numeric(18,6)")
                .HasPrecision(18, 6);

            b.Property<bool>("IsCurrent")
                .HasColumnType("boolean");

            b.Property<string>("ExplanationJson")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex(new[] { "OrderId" }, "ux_assignments_current_order").IsUnique().HasFilter("\"IsCurrent\"");
            b.HasIndex(new[] { "OrderId" }, "ix_assignments_order");
            b.HasIndex(new[] { "CreatedAt" }, "ix_assignments_created_at");

            b.ToTable("assignments");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.AuditEntry", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<string>("Actor")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<string>("Action")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("Entity")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("EntityId")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("DataJson")
                .HasColumnType("jsonb");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("CreatedAt");

            b.ToTable("audit_entries");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.Executor", b =>
        {
            b.Property<long>("Id")
                .HasColumnType("bigint");

            b.Property<string>("FullName")
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnType("character varying(300)");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean");

            b.Property<int?>("DailyLimit")
                .HasColumnType("integer");

            b.Property<decimal>("QualificationWeight")
                .HasColumnType("numeric(10,3)")
                .HasPrecision(10, 3);

            b.Property<string>("AttributesJson")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("executors");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.FieldDefinition", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("Owner")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(48)
                .HasColumnType("character varying(48)");

            b.Property<string>("Label")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<string[]>("Options")
                .IsRequired()
                .HasColumnType("text[]");

            b.HasKey("Id");

            b.HasIndex("Owner", "Key").IsUnique();

            b.ToTable("field_definitions");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.Order", b =>
        {
            b.Property<long>("Id")
                .HasColumnType("bigint");

            b.Property<long?>("ParentId")
                .HasColumnType("bigint");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<decimal>("Weight")
                .HasColumnType("numeric(10,3)")
                .HasPrecision(10, 3);

            b.Property<string>("AttributesJson")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<long?>("ExecutorId")
                .HasColumnType("bigint");

            b.Property<string>("PendingReason")
                .HasMaxLength(300)
                .HasColumnType("character varying(300)");

            b.Property<DateTimeOffset>("ReceivedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("AssignedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("ClosedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("ParentId");
            b.HasIndex("Status", "ExecutorId");

            b.ToTable("orders");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.OutboxMessage", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<long>("OrderId")
                .HasColumnType("bigint");

            b.Property<long>("ExecutorId")
                .HasColumnType("bigint");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("NextAttemptAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("SentAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("Attempts")
                .HasColumnType("integer");

            b.Property<string>("LastError")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.HasKey("Id");

            b.HasIndex("SentAt", "NextAttemptAt");

            b.ToTable("outbox_messages");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.Rule", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(160)
                .HasColumnType("character varying(160)");

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean");

            b.Property<int>("Priority")
                .HasColumnType("integer");

            b.Property<string>("OrderField")
                .IsRequired()
                .HasMaxLength(48)
                .HasColumnType("character varying(48)");

            b.Property<string>("Operator")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("Target")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<string>("ExecutorField")
                .HasMaxLength(48)
                .HasColumnType("character varying(48)");

            b.Property<string>("ExecutorFieldUpper")
                .HasMaxLength(48)
                .HasColumnType("character varying(48)");

            b.Property<string>("ValueJson")
                .HasColumnType("jsonb");

            b.Property<bool>("IsStrict")
                .HasColumnType("boolean");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("rules");
        });

        modelBuilder.Entity("ExecutorBalancer.Domain.WeightRule", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean");

            b.Property<int>("Priority")
                .HasColumnType("integer");

            b.Property<string>("OrderField")
                .IsRequired()
                .HasMaxLength(48)
                .HasColumnType("character varying(48)");

            b.Property<string>("Operator")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("ValueJson")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<decimal>("Weight")
                .HasColumnType("numeric(10,3)")
                .HasPrecision(10, 3);

            b.HasKey("Id");

            b.ToTable("weight_rules");
        });
    }
}
